local MASQUE = LibStub("Masque", true)
if not MASQUE then
	return
end

local AddOn, _ = ...
local Version = GetAddOnMetadata(AddOn, "Version")

--[[ Default ]]

MASQUE:AddSkin("Neuron: Default", {
	Description = "The default Masque skin for the Neuron World of Warcraft add-on",
	Author = "Soyier",
	Version = Version,
	Shape = "Square",
	Masque_Version = 80200,

	-- Layer Settings
	Backdrop = {
		Width = 42,
		Height = 42,
		Color = {0, 0, 0, .6},
		DrawLayer = "BACKGROUND",
		DrawLevel = -1,
		Point = "CENTER",
		RelPoint = "CENTER",
		OffsetX = 0,
		OffsetY = 0,
		UseColor = true,
		Texture = [[Interface\AddOns\Masque_Neuron\Default\Backdrop]],
	},
	Icon = {
		Width = 29,
		Height = 29,
		TexCoords = {0.08, 0.92, 0.08, 0.92},
		DrawLayer = "BACKGROUND",
		DrawLevel = 0,
		Point = "CENTER",
		RelPoint = "CENTER",
		OffsetX = 0,
		OffsetY = 0,
	},
	Flash = {
		Width = 42,
		Height = 42,
		Texture = [[Interface\Buttons\UI-QuickslotRed]],
		TexCoords = {0.2, 0.8, 0.2, 0.8},
		Color = {1, 1, 1, 0.75},
		BlendMode = "BLEND",
		DrawLayer = "ARTWORK",
		DrawLevel = 1,
		Point = "CENTER",
		RelPoint = "CENTER",
		OffsetX = 0,
		OffsetY = 0,
	},
	Cooldown = {
		Width = 28,
		Height = 28,
		Color = {0, 0, 0, 0.6},
		Point = "CENTER",
		RelPoint = "CENTER",
		OffsetX = 0,
		OffsetY = 0,
	},
	Normal = {
		Width = 42,
		Height = 42,
		Color = {0.2, 0.2, 0.2, 1},
		Texture = [[Interface\AddOns\Masque_Neuron\Default\Normal]],
	},
	Pushed = {
		Width = 42,
		Height = 42,
		BlendMode = "BLEND",
		DrawLayer = "ARTWORK",
		DrawLevel = 0,
		Point = "CENTER",
		RelPoint = "CENTER",
		OffsetX = 0,
		OffsetY = 0,
		Color = {1, 1, 1, .5},
		Texture = [[Interface\AddOns\Masque_Neuron\Default\Overlay]],
	},
	Border = {
		Width = 42,
		Height = 42,
		BlendMode = "ADD",
		DrawLayer = "OVERLAY",
		DrawLevel = 0,
		Point = "CENTER",
		RelPoint = "CENTER",
		OffsetX = 0,
		OffsetY = 0,
		Texture = [[Interface\AddOns\Masque_Neuron\Default\Border]],
	},
	Disabled = {
		Width = 42,
		Height = 42,
		BlendMode = "BLEND",
		Color = {1, 0, 0, 1},
		Texture = [[Interface\AddOns\Masque_Neuron\Default\Border]],
	},
	Checked = {
		Width = 42,
		Height = 42,
		BlendMode = "ADD",
		DrawLayer = "OVERLAY",
		DrawLevel = 0,
		Color = {1, 1, 1, 0.5},
		Point = "CENTER",
		RelPoint = "CENTER",
		OffsetX = 0,
		OffsetY = 0,
		Texture = [[Interface\AddOns\Masque_Neuron\Default\Border]],
	},
	AutoCastable = {
		Texture = [[Interface\Buttons\UI-AutoCastableOverlay]],
		BlendMode = "BLEND",
		DrawLayer = "OVERLAY",
		DrawLevel = 1,
		Width = 42,
		Height = 42,
		Point = "CENTER",
		RelPoint = "CENTER",
		OffsetX = 0.5,
		OffsetY = -0.5,
	},
	Shine = {
		Width = 32,
		Height = 32,
		OffsetX = 1,
		OffsetY = -1,
		AboveNormal = true,
	},
	Highlight = {
		Width = 37,
		Height = 37,
		BlendMode = "ADD",
		DrawLayer = "HIGHLIGHT",
		Color = {1, 1, 1, 0.75},
		Point = "CENTER",
		RelPoint = "CENTER",
		OffsetX = 0.5,
		OffsetY = -0.5,
		Texture = [[Interface\AddOns\Masque_Neuron\Default\Highlight]],
	},
	Gloss = {
		Width = 42,
		Height = 42,
		BlendMode = "ADD",
		Color = {1, 1, 1, .15},
		Texture = [[Interface\AddOns\Masque_Neuron\Default\Gloss]],
	},
	HotKey = {
		JustifyH = "RIGHT",
		JustifyV = "MIDDLE",
		DrawLayer = "ARTWORK",
		Width = 42,
		Height = 10,
		Point = "TOPRIGHT",
		RelPoint = "TOPRIGHT",
		OffsetX = -3,
		OffsetY = -4,
	},
	Count = {
		JustifyH = "RIGHT",
		JustifyV = "MIDDLE",
		DrawLayer = "ARTWORK",
		Width = 42,
		Height = 10,
		Point = "BOTTOMRIGHT",
		RelPoint = "BOTTOMRIGHT",
		OffsetX = -3,
		OffsetY = 4,
	},
	Name = {
		Width = 42,
		Height = 10,
		JustifyH = "CENTER",
		JustifyV = "BOTTOM",
		OffsetY = 3,
	},
	Duration = {
		JustifyH = "CENTER",
		JustifyV = "MIDDLE",
		DrawLayer = "ARTWORK",
		Width = 42,
		Height = 10,
		Point = "TOP",
		RelPoint = "BOTTOM",
		OffsetX = 0,
		OffsetY = -2,
	},
}, true)